### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by indexmod** [johnpeart/dept-of-bad-ideas#1]
Dear John, I just started following you in GitHub and am writing with a little friendly request.

I copied  "The Department of Bad Ideas" repository because it is the most elegant of those found. On this basis, I want to create a light version (podcast in GitHub Pages on Jekyll) with extra simplified styles.

I would be grateful if you would suggest (If it is possible) how to carefully get everything connected with the SASS to replace it with a regular CSS without breaking anything. I am too weak in Ruby and the Terminal so I am editing only with GitHub desktop app by hands. 

With thanks in advance, 

Andrei Deinichenko @indexmod

deinichenko.a@gmail.com

**Comment by johnpeart** [comment]
Hi Andrei

Sorry for the slow reply. 

I'm not sure I fully follow your question, but in order to replace the styles and not use SASS, delete the `_sass` folder, and then replace  `/assets/styles/styles.scss` with a file called `styles.css`. This would strip out all the styles and you could then code it from scratch.

Hope that helps.

JP
